import { jsPDF } from 'jspdf';
import type { TaxResult } from '../domain/tax';
import type { TaxReturn, T4Slip, T4ASlip, T5Slip, T2125Data, CapitalGainsTransaction } from '../context/TaxReturnContext';

type Slip = T4Slip | T4ASlip | T5Slip | T2125Data | CapitalGainsTransaction;

interface Profile {
  firstName: string;
  lastName: string;
  sin: string;
  dateOfBirth: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
}

interface ExportOptions {
  maskSIN?: boolean;
}

export function generateTaxSummaryPDF(
  profile: Profile,
  taxResult: TaxResult,
  taxYear: number,
  options: ExportOptions = { maskSIN: true }
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Helper functions
  const centerText = (text: string, y: number, size: number = 12) => {
    doc.setFontSize(size);
    const textWidth = doc.getTextWidth(text);
    doc.text(text, (pageWidth - textWidth) / 2, y);
  };

  const addRow = (label: string, value: string, y: number, bold: boolean = false) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(label, 20, y);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.text(value, pageWidth - 20, y, { align: 'right' });
  };

  const formatCurrency = (amount: number): string => {
    return new Intl.NumberFormat('en-CA', {
      style: 'currency',
      currency: 'CAD'
    }).format(amount);
  };

  const maskSIN = (sin: string): string => {
    const digits = sin.replace(/\D/g, '');
    return `***-***-${digits.slice(-3)}`;
  };

  // Header
  doc.setFillColor(13, 95, 43);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  centerText('TaxSimple', 20, 24);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  centerText(`${taxYear} Tax Summary`, 32, 14);

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Personal Information
  let y = 55;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Personal Information', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${profile.firstName} ${profile.lastName}`, 20, y);
  y += 7;
  doc.text(`SIN: ${options.maskSIN ? maskSIN(profile.sin) : profile.sin}`, 20, y);
  y += 7;
  doc.text(`Date of Birth: ${profile.dateOfBirth}`, 20, y);
  y += 7;
  doc.text(`Address: ${profile.address}, ${profile.city}, ${profile.province} ${profile.postalCode}`, 20, y);
  y += 15;

  // Tax Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculation Summary', 20, y);
  y += 12;

  // Draw table
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;

  addRow('Total Income', formatCurrency(taxResult.totalIncome), y);
  y += 8;
  addRow('Total Deductions', `(${formatCurrency(taxResult.totalDeductions)})`, y);
  y += 8;

  doc.line(20, y, pageWidth - 20, y);
  y += 8;
  addRow('Taxable Income', formatCurrency(taxResult.taxableIncome), y, true);
  y += 12;

  addRow('Federal Tax', formatCurrency(taxResult.federalTax), y);
  y += 8;
  addRow(`Provincial Tax (${taxResult.provinceName})`, formatCurrency(taxResult.provincialTax), y);
  y += 8;

  if (taxResult.healthPremium > 0) {
    addRow('Ontario Health Premium', formatCurrency(taxResult.healthPremium), y);
    y += 8;
  }

  doc.line(20, y, pageWidth - 20, y);
  y += 8;
  addRow('Total Tax', formatCurrency(taxResult.totalTax), y, true);
  y += 8;
  addRow('Tax Already Paid', `(${formatCurrency(taxResult.totalWithheld)})`, y);
  y += 12;

  // Refund/Owing box
  if (taxResult.isRefund) {
    doc.setFillColor(209, 250, 229);
  } else {
    doc.setFillColor(254, 226, 226);
  }
  doc.rect(20, y, pageWidth - 40, 20, 'F');
  y += 14;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  if (taxResult.isRefund) {
    doc.setTextColor(6, 95, 70);
  } else {
    doc.setTextColor(153, 27, 27);
  }
  const resultLabel = taxResult.isRefund ? 'Your Refund' : 'Amount Owing';
  const resultValue = formatCurrency(Math.abs(taxResult.refundOrOwing));
  doc.text(resultLabel, 25, y);
  doc.text(resultValue, pageWidth - 25, y, { align: 'right' });

  // Reset colors
  doc.setTextColor(0, 0, 0);
  y += 25;

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by TaxSimple on ${new Date().toLocaleDateString()}`, 20, y);
  y += 5;
  doc.text('This is a summary for your records. File your return with the CRA using certified software.', 20, y);

  // Save
  doc.save(`TaxSimple_${taxYear}_Summary.pdf`);
}

export function exportTaxDataJSON(
  profile: Profile,
  taxReturn: TaxReturn,
  taxResult: TaxResult
): void {
  const exportData = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    taxYear: taxReturn.year,
    profile: {
      firstName: profile.firstName,
      lastName: profile.lastName,
      dateOfBirth: profile.dateOfBirth,
      province: profile.province,
      city: profile.city,
      postalCode: profile.postalCode
      // SIN intentionally excluded
    },
    income: {
      slips: taxReturn.slips.map((slip: Slip) => {
        if (slip.type === 'T4') {
          return {
            type: slip.type,
            employerName: slip.employerName,
            employmentIncome: slip.boxes[14],
            cppContributions: slip.boxes[16],
            eiPremiums: slip.boxes[18],
            taxDeducted: slip.boxes[22]
          };
        }
        return { type: slip.type };
      }),
      other: taxReturn.otherIncome
    },
    deductions: taxReturn.deductions,
    credits: taxReturn.credits,
    result: {
      totalIncome: taxResult.totalIncome,
      totalDeductions: taxResult.totalDeductions,
      taxableIncome: taxResult.taxableIncome,
      federalTax: taxResult.federalTax,
      provincialTax: taxResult.provincialTax,
      healthPremium: taxResult.healthPremium,
      totalTax: taxResult.totalTax,
      totalWithheld: taxResult.totalWithheld,
      refundOrOwing: taxResult.refundOrOwing,
      isRefund: taxResult.isRefund
    }
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `TaxSimple_${taxReturn.year}_Data.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
